#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: python:3.9-buster

options:
  max-time: 15
  size: 2x
definitions:
  services:
    docker:
      memory: 7000
pipelines:
  default:
    - step:
        name: Build
        caches:
          - docker
          - pip
        script:
          - docker build -t kmw:solrkafka-test -f Dockerfile-test .
          - docker save --output solrkafka-test.docker kmw:solrkafka-test
          - pip install docker-compose
        after-script:
          # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
          - pipe: atlassian/checkstyle-report:0.2.0
        services:
          - docker
        artifacts:
          - solrkafka-test.docker
    - parallel:
        - step:
            name: Single Node Test
            caches:
              - pip
            services:
              - docker
            script:
              - docker load --input ./solrkafka-test.docker
              - pip install docker-compose
              - docker-compose -f docker-compose-test.yml --verbose up -d --no-color
              - sleep 20
              - docker exec -t solrkafka_solr java -cp "/var/solr/data/lib/*" com.kmwllc.solr.solrkafka.test.SingleNodeTest -d
            after-script:
              - docker commit solrkafka_solr kmw:solrkafka-test-export
              - docker save --output solrkafka-test-export.docker kmw:solrkafka-test-export
              - tar -czvf image.tar.gz solrkafka-test-export.docker
              - docker cp solrkafka_solr:/var/solr/logs/ ./logs
              - docker-compose -f docker-compose-test.yml --verbose down -v --remove-orphans
            artifacts:
              - logs/*
              - iamge.tar.gz
        - step:
            name: Multi Node Test Normal Routing
            caches:
              - pip
            services:
              - docker
            script:
              - docker load --input ./solrkafka-test.docker
              - pip install docker-compose
              - docker-compose -f docker-compose-cloud-test.yml --verbose up -d --no-color
              - sleep 20
              - docker exec -t solrkafka_solr_8983 java -cp "/var/solr/data/lib/*" com.kmwllc.solr.solrkafka.test.MultiNodeTest -d
            after-script:
              - docker commit solrkafka_solr_8983 kmw:solrkafka-test-export-8983
              - docker commit solrkafka_solr_7574 kmw:solrkafka-test-export-7574
              - docker save --output solrkafka-test-export-8983.docker kmw:solrkafka-test-export-8983
              - docker save --output solrkafka-test-export-7574.docker kmw:solrkafka-test-export-7574
              - tar -czvf images.tar.gz solrkafka-test-export-8983.docker solrkafka-test-export-7574.docker
              - docker cp solrkafka_solr_8983:/var/solr/logs/ ./logs-8983
              - docker cp solrkafka_solr_7574:/var/solr/logs/ ./logs-7574
              - docker-compose -f docker-compose-cloud-test.yml --verbose down -v --remove-orphans
            artifacts:
              - logs-8983/*
              - logs-7574/*
              - images.tar.gz
        - step:
            name: Multi Node Test All Shard Routing
            caches:
              - pip
            services:
              - docker
            script:
              - docker load --input ./solrkafka-test.docker
              - pip install docker-compose
              - docker-compose -f docker-compose-cloud-test.yml --verbose up -d --no-color
              - sleep 20
              - docker exec -t solrkafka_solr_8983 java -cp "/var/solr/data/lib/*" com.kmwllc.solr.solrkafka.test.MultiNodeTest -d -i
            after-script:
              - docker commit solrkafka_solr_8983 kmw:solrkafka-test-export-8983
              - docker commit solrkafka_solr_7574 kmw:solrkafka-test-export-7574
              - docker save --output solrkafka-test-export-8983.docker kmw:solrkafka-test-export-8983
              - docker save --output solrkafka-test-export-7574.docker kmw:solrkafka-test-export-7574
              - tar -czvf images.tar.gz solrkafka-test-export-8983.docker solrkafka-test-export-7574.docker
              - docker cp solrkafka_solr_8983:/var/solr/logs/ ./logs-8983
              - docker cp solrkafka_solr_7574:/var/solr/logs/ ./logs-7574
              - docker-compose -f docker-compose-cloud-test.yml --verbose down -v --remove-orphans
            artifacts:
              - logs-8983/*
              - logs-7574/*
              - images.tar.gz
        - step:
            name: Multi Node Kill Test
            caches:
              - pip
            services:
              - docker
            script:
              - docker load --input ./solrkafka-test.docker
              - pip install docker-compose
              - docker-compose -f docker-compose-cloud-test.yml --verbose up -d --no-color
              - sleep 20
              - docker exec -t solrkafka_solr_8983 java -cp "/var/solr/data/lib/*" com.kmwllc.solr.solrkafka.test.MultiNodeKillTest -d
            after-script:
              - docker commit solrkafka_solr_8983 kmw:solrkafka-test-export-8983
              - docker commit solrkafka_solr_7574 kmw:solrkafka-test-export-7574
              - docker save --output solrkafka-test-export-8983.docker kmw:solrkafka-test-export-8983
              - docker save --output solrkafka-test-export-7574.docker kmw:solrkafka-test-export-7574
              - tar -czvf images.tar.gz solrkafka-test-export-8983.docker solrkafka-test-export-7574.docker
              - docker cp solrkafka_solr_8983:/var/solr/logs/ ./logs-8983
              - docker cp solrkafka_solr_7574:/var/solr/logs/ ./logs-7574
              - docker-compose -f docker-compose-cloud-test.yml --verbose down -v --remove-orphans
            artifacts:
              - logs-8983/*
              - logs-7574/*
              - images.tar.gz
        - step:
            name: Multi Node Kill Test All Shard Routing
            caches:
              - pip
            services:
              - docker
            script:
              - docker load --input ./solrkafka-test.docker
              - pip install docker-compose
              - docker-compose -f docker-compose-cloud-test.yml --verbose up -d --no-color
              - sleep 20
              - docker exec -t solrkafka_solr_8983 java -cp "/var/solr/data/lib/*" com.kmwllc.solr.solrkafka.test.MultiNodeKillTest -d -i
            after-script:
              - docker commit solrkafka_solr_8983 kmw:solrkafka-test-export-8983
              - docker commit solrkafka_solr_7574 kmw:solrkafka-test-export-7574
              - docker save --output solrkafka-test-export-8983.docker kmw:solrkafka-test-export-8983
              - docker save --output solrkafka-test-export-7574.docker kmw:solrkafka-test-export-7574
              - tar -czvf images.tar.gz solrkafka-test-export-8983.docker solrkafka-test-export-7574.docker
              - docker image ls
              - docker cp solrkafka_solr_8983:/var/solr/logs/ ./logs-8983
              - docker cp solrkafka_solr_7574:/var/solr/logs/ ./logs-7574
              - docker-compose -f docker-compose-cloud-test.yml --verbose down -v --remove-orphans
            artifacts:
              - logs-8983/*
              - logs-7574/*
              - images.tar.gz
#        - step:
#            name: Failure Test
#            caches:
#              - pip
#            services:
#              - docker
#            script:
#              - docker load --input ./solrkafka-test.docker
#              - pip install docker-compose
#              - docker-compose -f docker-compose-cloud-test.yml --verbose up -d --no-color
#              - sleep 20
#              - docker exec -t solrkafka_solr_8983 java -cp "/var/solr/data/lib/*" com.kmwllc.solr.solrkafka.test.FailureTest
#            after-script:
#              - docker-compose -f docker-compose-cloud-test.yml --verbose down -v --remove-orphans
