FROM maven:3-openjdk-11 AS builder

COPY pom.xml /solrkafka/
WORKDIR /solrkafka
RUN mvn -B verify clean --fail-never
COPY . /solrkafka/
RUN mvn -B verify --file pom.xml

FROM solr:8.8.1

COPY --from=builder /solrkafka/target/solrkafka-*.jar /var/solr/data/lib/

USER root

RUN cp -r server/solr/configsets/_default server/solr/configsets/testconfig
COPY src/main/resources/test_configs/solrconfig.xml server/solr/configsets/testconfig/conf/
COPY src/main/resources/test_configs/solrconfig-routing.xml server/solr/configsets/testconfig/conf/

USER $SOLR_USER
