version: "3.9"
services:
  solr-8983:
    image: kmw:solrkafka-test
    container_name: solrkafka_solr_8983
    build:
      dockerfile: Dockerfile-test
      context: .
    entrypoint: "/usr/local/openjdk-11/bin/java"
    command: ["-cp", "/var/solr/data/lib/*", "com.kmwllc.solr.solrkafka.test.SolrManager"]
    environment:
      ZK_HOST: zookeeper:2181
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8983:8983"
    networks:
      - solrkafka
    deploy:
      resources:
        limits:
          memory: 3GB
        reservations:
          memory: 3GB

  solr-7574:
    image: kmw:solrkafka-test
    container_name: solrkafka_solr_7574
    build:
      dockerfile: Dockerfile-test
      context: .
    environment:
      ZK_HOST: zookeeper:2181
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "7574:8983"
    networks:
      - solrkafka
    deploy:
      resources:
        limits:
          memory: 2GB
        reservations:
          memory: 2GB

  zookeeper:
    image: zookeeper:3.6.2
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    tmpfs:
      - /data
      - /datalog
    networks:
      - solrkafka
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "testtopic:10:1"
      KAFKA_MESSAGE_MAX_BYTES: 250000000
      KAFKA_MAX_REQUEST_SIZE: 250000000
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 250000000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /kafka
    networks:
      - solrkafka
    depends_on:
      - zookeeper

networks:
  solrkafka:
