version: "3.9"
services:
  solr:
    image: kmw:solrkafka-test
    build:
      dockerfile: Dockerfile-test
      context: .
    environment:
      ZK_HOST: zookeeper:2181
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8983:8983"
    networks:
      - solrkafka
    deploy:
      resources:
        limits:
          memory: 3GB
        reservations:
          memory: 3GB

  zookeeper:
    image: zookeeper:3.6.2
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    tmpfs:
      - /data
      - /datalog
    networks:
      - solrkafka
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "testtopic:10:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /kafka
    networks:
      - solrkafka
    depends_on:
      - zookeeper

networks:
  solrkafka:
